In [9]:
import pandas as pd
import pyreadstat

In [17]:
result = pd.concat(
    [
        pyreadstat.read_sas7bdat('../data/HN21_ALL.sas7bdat')[0],
        pyreadstat.read_sas7bdat('../data/HN20_ALL.sas7bdat')[0],
        pyreadstat.read_sas7bdat('../data/HN19_ALL.sas7bdat')[0],
        pyreadstat.read_sas7bdat('../data/HN18_ALL.sas7bdat')[0],
        pyreadstat.read_sas7bdat('../data/hn17_all.sas7bdat')[0],
        pyreadstat.read_sas7bdat('../data/hn16_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn15_all.sas7bdat')[0],
        pyreadstat.read_sas7bdat('../data/hn14_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn13_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn12_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn11_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn10_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn09_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn08_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn07_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn05_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn01_all.sas7bdat', encoding="latin1")[0],
        pyreadstat.read_sas7bdat('../data/hn98_all.sas7bdat', encoding="latin1")[0],
    ]
)

def label_cardinal_number(year):
    year = int(year)
    if year >= 2019 and year <= 2021:
        return 8
    elif year >= 2016 and year <= 2018:
        return 7
    elif year >= 2013 and year <= 2015:
        return 6
    elif year >= 2010 and year <= 2012:
        return 5
    elif year >= 2007 and year <= 2009:
        return 4
    elif year == 2005:
        return 3
    elif year == 2001:
        return 2
    elif year == 1998:
        return 1
    else:
        return 0

In [18]:
result[result['year'] == 1998]

,mod_d,ID,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,F_pineap,F_frt_jc,F_kc_rds,F_lett,F_leek,F_ssm_lv,F_garlic,F_mallow,F_dropwt,F_broc
0,2019.03.06.,NaN,NaN,1998.0,1.0,1.0,NaN,101,2.0,50.0,...,8.0,2.0,8.0,7.0,4.0,8.0,3.0,8.0,5.0,2.0
1,2019.03.06.,NaN,NaN,1998.0,1.0,1.0,NaN,101,1.0,22.0,...,0.0,9.0,9.0,8.0,9.0,9.0,7.0,1.0,5.0,4.0
2,2019.03.06.,NaN,NaN,1998.0,1.0,1.0,NaN,101,1.0,32.0,...,0.0,3.0,8.0,8.0,7.0,7.0,7.0,6.0,6.0,6.0
3,2019.03.06.,NaN,NaN,1998.0,1.0,1.0,NaN,101,2.0,31.0,...,1.0,3.0,7.0,4.0,3.0,3.0,4.0,1.0,1.0,2.0
4,2019.03.06.,NaN,NaN,1998.0,1.0,1.0,NaN,101,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39055,2019.03.06.,NaN,NaN,1998.0,11.0,2.0,NaN,802,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39056,2019.03.06.,NaN,NaN,1998.0,11.0,2.0,NaN,802,1.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39057,2019.03.06.,NaN,NaN,1998.0,11.0,2.0,NaN,802,2.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39058,2019.03.06.,NaN,NaN,1998.0,11.0,2.0,NaN,802,1.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39059,2019.03.06.,NaN,NaN,1998.0,11.0,2.0,NaN,802,2.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# 새로운 라벨을 생성하여 새로운 컬럼에 저장
result['cardinal_number'] = result['year'].apply(label_cardinal_number)
result['cardinal_number']

/var/folders/3y/hj83hdwn2nn49jp7jks64t480000gn/T/ipykernel_8353/1119135523.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  result['cardinal_number'] = result['year'].apply(label_cardinal_number)

0        8
1        8
2        8
3        8
4        8
        ..
39055    1
39056    1
39057    1
39058    1
39059    1
Name: cardinal_number, Length: 231264, dtype: int64

In [21]:
result.groupby('cardinal_number').size()

cardinal_number
1    39060
2    37878
3    34145
4    24871
5    25534
6    22948
7    24269
8    22559
dtype: int64

In [22]:
result.to_csv('../data/HN_cardinal_1_8.csv', index=False)

In [2]:
import pandas as pd

df = pd.read_csv('../data/v1/HN__11_21_all.csv')
df.shape

/var/folders/3y/hj83hdwn2nn49jp7jks64t480000gn/T/ipykernel_8353/310488906.py:3: DtypeWarning: Columns (1,37,38,105,135,140,208,260,285,311,380,386,427,513,526,528,530,567,585,660,662,664,669,673,779,780,784,867,868,869,870,891,897,908,918,974,978,984,991,998,1008,1017,1019,1023,1025,1132,1134,1147,1149,1157,1162,1163,1173,1176,1192,1198,1213,1214,1215,1282,1290,1305,1308,1318,1326,1346,1367,1429,1436) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/v1/HN__11_21_all.csv')

(86352, 1516)

In [ ]:
y = df.query("BP6_31 == 1")["BP6_31"]
y

In [3]:
targets_of_scan = [
    "ID",
    "ID_fam",
    "year",
    "sex",
    "age",
    "incm",
    "ho_incm",
    "incm5",
    "ho_incm5",
    "edu",
    "occp",
    "cfam",
    "genertn",
    "allownc",
    "house",
    "live_t",
    "ainc_unit1",
    "ainc_1",
    "ainc",
    "marri_1",
    "marri_2",
    "fam_rela",
    "D_1_1",
    "D_2_1",
    "D_2_wk",
    "DI1_dg",
    "DI1_pr",
    "DI1_pt",
    "DI1_2",
    "DI2_dg",
    "DI2_pr",
    "DI2_pt",
    "DI2_2",
    "DI3_dg",
    "DI3_pr",
    "DI3_pt",
    "DI3_2",
    "DI4_dg",
    "DI4_pr",
    "DI4_pt",
    "DM1_dg",
    "DM1_pr",
    "DM1_pt",
    "DM2_dg",
    "DM2_pr",
    "DM2_pt",
    "DM3_dg",
    "DM3_pr",
    "DM3_pt",
    "DM4_dg",
    "DM4_pr",
    "DM4_pt",
    "DJ2_dg",
    "DJ2_pr",
    "DJ2_pt",
    "DJ4_dg",
    "DJ4_pr",
    "DJ4_pt",
    "DJ4_3",
    "DE2_dg",
    "DE2_pr",
    "DE2_pt",
    "DE1_dg",
    "DE1_pr",
    "DE1_pt",
    "DC1_dg",
    "DC1_pr",
    "DC1_pt",
    "DC2_dg",
    "DC2_pr",
    "DC2_pt",
    "DC3_dg",
    "DC3_pr",
    "DC3_pt",
    "DC4_dg",
    "DC4_pr",
    "DC4_pt",
    "DC5_dg",
    "DC5_pr",
    "DC5_pt",
    "DC6_dg",
    "DC6_pr",
    "DC6_pt",
    "DC7_dg",
    "DC7_pr",
    "DC7_pt",
    "DC11_dg",
    "DC11_pr",
    "DC11_pt",
    "DC12_dg",
    "DC12_pr",
    "DC12_pt",
    "DL1_dg",
    "DL1_pr",
    "DL1_pt",
    "DJ8_dg",
    "DJ8_pr",
    "DJ8_pt",
    "DJ6_dg",
    "DJ6_pr",
    "DJ6_pt",
    "DH4_dg",
    "DH4_pr",
    "DH4_pt",
    "DH2_dg",
    "DH2_pr",
    "DH2_pt",
    "DH3_dg",
    "DH3_pr",
    "DH3_pt",
    "DH6_dg",
    "DH6_pr",
    "DH6_pt",
    "DH7_dg",
    "DH7_pr",
    "DH7_pt",
    "DN1_dg",
    "DN1_pr",
    "DN1_pt",
    "DK8_dg",
    "DK8_pr",
    "DK8_pt",
    "DK9_dg",
    "DK9_pr",
    "DK9_pt",
    "DK4_dg",
    "DK4_pr",
    "DK4_pt",
    "DM8_dg",
    "DM8_pr",
    "DM8_pt",
    "M_2_yr",
    "BH9_11",
    "BH1",
    "BH2_61",
    "BH2_62",
    "LQ4_00",
    "LQ4_01",
    "LQ4_02",
    "LQ4_03",
    "LQ4_04",
    "LQ4_05",
    "LQ4_06",
    "LQ4_07",
    "LQ4_08",
    "LQ4_09",
    "LQ4_10",
    "LQ4_11",
    "LQ4_12",
    "LQ4_13",
    "LQ4_14",
    "LQ4_15",
    "LQ4_16",
    "LQ4_21",
    "LQ4_22",
    "LQ4_25",
    "LQ4_26",
    "LQ4_27",
    "LQ4_28",
    "LQ4_29",
    "LQ4_23",
    "LQ1_sb",
    "LQ1_mn",
    "LQ2_ab",
    "LQ2_mn",
    "LQ_1EQL",
    "LQ_2EQL",
    "LQ_3EQL",
    "LQ_4EQL",
    "LQ_5EQL",
    "LQ_1HT",
    "LQ_2HT",
    "LQ_3HT",
    "LQ_4HT",
    "LQ_5HT",
    "LQ_6HT",
    "LQ_7HT",
    "LQ_8HT",
    "MH1_yr",
    "MH1_1",
    "educ",
    "graduat",
    "EC1_1",
    "EC_occp",
    "EC_stt_1",
    "EC_stt_2",
    "EC_wht_0",
    "EC_wht_23",
    "EC_wht_5",
    "EC_pedu_1",
    "EC_pedu_2",
    "BO1",
    "BO1_1",
    "BO1_2",
    "BO1_3",
    "BO2_1",
    "BO3_01",
    "BO3_02",
    "BO3_03",
    "BO3_14",
    "BO3_05",
    "BO3_04",
    "BO3_12",
    "BO3_07",
    "BO3_09",
    "BO3_10",
    "BO3_11",
    "BD1",
    "BD2",
    "BD1_11",
    "BD2_1",
    "BD7_5",
    "BD7_61",
    "BD7_62",
    "BD7_63",
    "BD7_64",
    "BD7_65",
    "BD7_66",
    "BA2_12",
    "BA2_13",
    "BA2_14",
    "BA2_2_1",
    "BA2_2_2",
    "BA2_2_3",
    "BA2_2_4",
    "BA2_2_5",
    "BA2_2_6",
    "BP16_1",
    "BP16_2",
    "BP16_11",
    "BP16_12",
    "BP16_13",
    "BP16_21",
    "BP16_23",
    "BS1_1",
    "BS2_2",
    "BS3_1",
    "BS3_2",
    "BS3_3",
    "BS6_2",
    "BS6_3",
    "BS6_4",
    "BS12_37",
    "BS12_47",
    "BS12_1",
    "BS12_2",
    "BS5_4",
    "BS5",
    "BS5_1",
    "BS8_2",
    "BS9_2",
    "BS13",
    "BE3_71",
    "BE3_72",
    "BE3_73",
    "BE3_81",
    "BE3_82",
    "BE3_83",
    "BE3_91",
    "BE3_92",
    "BE3_93",
    "BE3_75",
    "BE3_76",
    "BE3_77",
    "BE3_85",
    "BE3_86",
    "BE3_87",
    "BE8_1",
    "BE3_31",
    "BE3_32",
    "BE5_1",
    "pa_aerobic",
    "LW_ms",
    "LW_mp_a",
    "LW_ms_a",
    "LW_pr",
    "LW_pr_1",
    "LW_mt",
    "LW_mt_a1",
    "LW_mt_a2",
    "LW_br",
    "LW_oc",
    "HE_HPdr",
    "HE_DMdr",
    "HE_mens",
    "HE_prg",
    "HE_dprg",
    "HE_fh",
    "HE_HPfh1",
    "HE_HPfh2",
    "HE_HPfh3",
    "HE_HLfh1",
    "HE_HLfh2",
    "HE_HLfh3",
    "HE_IHDfh1",
    "HE_IHDfh2",
    "HE_IHDfh3",
    "HE_STRfh1",
    "HE_STRfh2",
    "HE_STRfh3",
    "HE_DMfh1",
    "HE_DMfh2",
    "HE_DMfh3",
    "HE_THfh1",
    "HE_THfh2",
    "HE_THfh3",
    "HE_HBfh1",
    "HE_HBfh2",
    "HE_HBfh3",
    "HE_rPLS",
    "HE_HP",
    "HE_ht",
    "HE_wt",
    "HE_wc",
    "HE_nc",
    "HE_BMI",
    "HE_obe",
    "HE_glu",
    "HE_HbA1c",
    "HE_insulin",
    "HE_DM_HbA1c",
    "HE_chol",
    "HE_HDL_st2",
    "HE_TG",
    "HE_LDL_drct",
    "HE_HCHOL",
    "HE_HTG",
    "HE_ast",
    "HE_alt",
    "HE_hepaB",
    "HE_hepaC",
    "HE_HB",
    "HE_HCT",
    "HE_anem",
    "HE_BUN",
    "HE_crea",
    "HE_WBC",
    "HE_RBC",
    "HE_Bplt",
    "HE_Uacid",
    "HE_df",
    "HE_dog",
    "HE_cat",
    "HE_birch",
    "HE_oak",
    "HE_Jhop",
    "HE_ragweed",
    "HE_Uph",
    "HE_Unitr",
    "HE_Usg",
    "HE_Upro",
    "HE_Uglu",
    "HE_Uket",
    "HE_Ubil",
    "HE_Ubld",
    "HE_Uro",
    'HE_Ucrea',
    'HE_UNa',
    'HE_Ualb',
    'HE_Ukal',
    'HE_Ucot',
    'HE_fvc',
    'HE_fvcp',
    'HE_fev1',
    'HE_fev1p',
    'HE_fev1fvc',
    'HE_fev6',
    'HE_fef25_75',
    'HE_pef',
    'HE_COPD',
    'HE_cough1',
    'HE_cough2',
    'HE_sput1',
    'HE_sput2',
    'HE_PFTdr',
    'HE_PFTag',
    'HE_PFTtr',
    'HE_PFThs',
    "O_pain",
    "O_ortho",
    "BM13",
    "BM13_1",
    "BM13_2",
    "BM13_3",
    "BM13_4",
    "BM13_5",
    "BM7",
    "O_chew_d",
    "BM8",
    "OR1_2",
    "MO4_00",
    'MO4_4',
    'MO4_9',
    'MO4_7',
    'MO4_8',
    'MO4_17',
    'MO4_17_1',
    'MO4_17_2',
    'MO4_11',
    'MO4_12',
    'MO4_18',
    'MO4_15',
    "BM14",
    "BM14_1",
    'T_ex',
    'T_Q_HR',
    'T_Q_HR_1',
    'T_Q_HR_2',
    'T_NQ_OCP',
    'T_Q_VN',
    'T_Q_VN_1',
    'T_Q_VN_2',
    'T_Q_DZ',
    'T_Q_DZ2',
    'T_Q_DZ3',
    'T_Q_DZ4',
    'T_Q_DZ5',
    'T_Q_DZ6',
    'T_Q_DZ7',
    'T_Q_CR',
    'T_Q_CR1',
    'T_Q_CR2',
    'T_Q_CR3',
    'T_Q_CR4',
    'T_Q_ALLE',
    'T_Q_SNST1',
    'T_Q_SNST2',
    'T_Q_SNST3',
    'T_Q_SNST4',
    'T_Q_SINU',
    'T_Q_SINU_1',
    'T_Q_VC',
    'T_Q_VC1',
    "T_IM_EX_R",
    'T_IM_EX_R_1',
    'T_IM_EX_L',
    'T_IM_EX_L_1',
    "T_VHIT_EX_R",
    "T_VHIT_EX_R_1",
    "T_VHIT_EX_L",
    "T_VHIT_EX_L_1",
    "T_VHIT_GA_R",
    'T_VHIT_GA_L',
    'T_VHIT_COR_R',
    "T_VHIT_COR_L",
    "E_ex",
    "E_Q_EX",
    "E_DG",
    "E_DG1",
    "E_PEO",
    "E_PEO_1",
    "E_DR",
    "E_DR1",
    "E_NWT",
    "E_RT",
    "E_CT",
    "E_CLU",
    "E_CLD",
    "E_CLT",
    "E_CL_pr",
    "E_CLC",
    "E_CLC_T",
    "E_EXC_1",
    "E_Cr_1",
    "E_Cl_1",
    "E_Dr_2_1",
    "E_Dl_2_1",
    "E_NMRC_r",
    'E_NMRC_l',
    "E_Pr_1",
    "E_Pl_1",
    "E_DM",
    "E_DME",
    "E_AMD",
    "E_EM",
    "E_MH",
    "E_RVO",
    "E_GR",
    "IAQ_Window",
    "IAQ_PM2_5",
    "IAQ_CO2",
    "IAQ_HCHO",
    "IAQ_TVOC",
    "IAQ_Benzene",
    "IAQ_Toluene",
    "IAQ_Ethylbenzene",
    "IAQ_Xylene",
    "IAQ_Styrene",
    "IAQ_PM2_5_atmos",
    "IAQ_01_Y",
    "IAQ_01_M",
    "IAQ_02",  
    "IAQ_02_1",
    "IAQ_02_2",
    "IAQ_02_3",
    "IAQ_02_4",
    "IAQ_02_5",
    "IAQ_02_6",
    "IAQ_03",
    "IAQ_04",
    "IAQ_05",
    "IAQ_06",
    "IAQ_08",
    #TODO 
]

targets_of_life_style = [
    #생활습관 축약버전
    "EC1_1",
    "EC_wht_23",
    "BO2_1",
    "BD1",
    "BD1_11",
    "BD2_1",
    "BA2_12",
    "BA2_13",
    "BA2_14",
    "BP16_1",
    "BP16_2",
    "BP16_11",
    "BP16_13",
    "BP16_21",
    "BP16_23",
    "BP1",
    "BP5",
    "BP6_10",
    "BP6_2",
    "BP6_31",
    "BP7",
    "BS3_1",
    "BS3_2",
    "BS12_47",
    "BS12_47_1",
    "BS5_4",
    "BS5",
    "BE3_71",
    "BE3_81",
    "BE3_91",
    "BE3_75",
    "BE3_76",
    "BE3_85",
    "BE3_86",
    "BE8_1",
    "BE3_31",
    "BE5_1",
    "pa_aerobic",
    "LW_ms",
    "LW_pr",
    "LW_pr_1",
    "LW_mt",
    "LW_mt_a1",
    "LW_br",
    "LW_oc",
    "BM1_1",
    "BM1_2",
    "BM1_3",
    "BM1_4",
    "BM1_5",
    "BM1_6",
    "BM1_7",
    "BM1_8",
    "BM2_1",
    "BM2_3",
    "BM2_2",
    "BM2_4",
    "BM2_5",
    "BM7",
    "T_Q_HR",
    "T_Q_HR_1",
    "T_NQ_OCP",
    "T_Q_VN",
    "T_Q_DZ",
    "T_Q_DZ5",
    "T_Q_CR",
    "E_RT",
    "E_CT",
    "E_CLU",
    "IAQ_03",
    "IAQ_04",
    "IAQ_05",
    "IAQ_06",
    "IAQ_06_1",
    "IAQ_06_2",
    "IAQ_06_3",
    "IAQ_07",
    "IAQ_08",
    "IAQ_08_1",
    "IAQ_08_1_1",
    "IAQ_10",
    "IAQ_11",
    "IAQ_11_2",
    "IAQ_11_2_1",
    "IAQ_13_1T",
    "IAQ_13_1F",
    "IAQ_13_2T",
    "IAQ_13_2F",
    "IAQ_13_3T",
    "IAQ_13_3F",
    "IAQ_13_4T",
    "IAQ_13_4F",
    "IAQ_14",
    "IAQ_15_1",
    "IAQ_15_2",
    "IAQ_15_3",
    "IAQ_15_4",
    "IAQ_15_5",
    "IAQ_16",
    "IAQ_17",
    "IAQ_18",
    "IAQ_22_1",
    "IAQ_22_2",
    "IAQ_22_3",
    "IAQ_23_1",
    "IAQ_23_2",
    "IAQ_24",
    "IAQ_28",
    "HE_sbp",
    "HE_dbp",
    "HE_HP",
    "HE_ht",
    "HE_wt",
    "HE_wc",
    "HE_nc",
    "HE_BMI",
    "HE_obe",
    "HE_glu",
    "HE_chol",
    "HE_HDL_st2",
    "HE_HB",
    "HE_HCT",
    "HE_BUN",
    "HE_crea",
    "HE_WBC",
    "HE_RBC",
    "HE_Bplt",
    "HE_Uacid",
    "HE_Uph",
    "HE_Unitr",
    "HE_Usg",
    "HE_Upro",
    "HE_Uglu",
    "HE_Uket",
    "HE_Ubil",
    "HE_Ubld",
    "HE_Uro",
    "L_BR_FQ",
    "L_LN_FQ",
    "L_DN_FQ",
    "L_BR_TO",
    "L_BR_WHO",
    "L_LN_TO",
    "L_LN_WHO",
    "L_DN_TO",
    "L_DN_WHO",
    "L_OUT_FQ",
    "LS_VEG1",
    "LS_VEG2",
    "LS_FRUIT",
    "LK_LB_CO",
    "LK_LB_US",
    "LK_LB_EF",
    "DQ_SODA",
    "DQ_CAFFEINE",
    "DQ_COFFEE",
    "DQ_SCOFFEE",
    "DQ_TEA",
    "DQ_STEA",
    "DQ_MILK",
    "DQ_SMILK",
    "DQ_YOGURT",
    "LS_SUP"
]

in_other_db = ['IAQ_Window', 'IAQ_PM2_5', 'IAQ_CO2', 'IAQ_HCHO', 'IAQ_TVOC', 'IAQ_Benzene', 'IAQ_Toluene', 'IAQ_Ethylbenzene', 'IAQ_Xylene', 'IAQ_Styrene', 'IAQ_PM2_5_atmos', 'IAQ_01_Y', 'IAQ_01_M', 'IAQ_02', 'IAQ_02_1', 'IAQ_02_2', 'IAQ_02_3', 'IAQ_02_4', 'IAQ_02_5', 'IAQ_02_6', 'IAQ_03', 'IAQ_04', 'IAQ_05', 'IAQ_06', 'IAQ_08', 'IAQ_06_1', 'IAQ_06_2', 'IAQ_06_3', 'IAQ_07', 'IAQ_08_1', 'IAQ_08_1_1', 'IAQ_10', 'IAQ_11', 'IAQ_11_2', 'IAQ_11_2_1', 'IAQ_13_1T', 'IAQ_13_1F', 'IAQ_13_2T', 'IAQ_13_2F', 'IAQ_13_3T', 'IAQ_13_3F', 'IAQ_13_4T', 'IAQ_13_4F', 'IAQ_14', 'IAQ_15_1', 'IAQ_15_2', 'IAQ_15_3', 'IAQ_15_4', 'IAQ_15_5', 'IAQ_16', 'IAQ_17', 'IAQ_18', 'IAQ_22_1', 'IAQ_22_2', 'IAQ_22_3', 'IAQ_23_1', 'IAQ_23_2', 'IAQ_24', 'IAQ_28', 'LS_SUP']
# for i in in_other_db:
#     print(i)

#가정 실내공기질 조사 자료는 HN_IAQ DB에 포함
#식생활조사 자료 중 식이보충제 문항은 HNYR_SUP (YR은 해당연도 두자리수) DB에 포함 
targets = list(set(targets_of_scan + targets_of_life_style) - set(in_other_db))

# #TODO counting
# a = [
#     # "BM1_1" ~ "BM1_8"
#     # T_HR500_RT ~ T_HR8000_LT
#     # T_IM_A~C_R/L
#     # IAQ_06_1N ~ IAQ_06_3N
# ]

# #TODO mean
# a = [
#     #"GS_mea_r_1" ~ "GS_mea_l_3"
# ]

# targets = list(set(targets_of_life_style) - set(in_other_db))
df[targets]

,DK8_dg,BO3_05,HE_Uket,HE_fh,BA2_12,LQ4_03,LQ4_15,LQ4_21,HE_Usg,HE_BMI,...,BE3_76,MO4_4,EC_wht_0,BP6_31,fam_rela,LQ4_27,BS8_2,BS2_2,HE_HB,edu
0,0.0,NaN,0.0,0.0,8.0,8.0,8.0,8.0,1.013,26.789017,...,8.0,1.0,2.0,2.0,1.0,8.0,2.0,888.0,15.2,3.0
1,0.0,NaN,0.0,0.0,2.0,8.0,8.0,8.0,1.014,25.506641,...,8.0,1.0,2.0,2.0,9.0,8.0,2.0,18.0,15.1,3.0
2,0.0,NaN,0.0,1.0,8.0,8.0,8.0,8.0,1.013,23.075711,...,8.0,8.0,2.0,2.0,1.0,8.0,2.0,888.0,13.3,2.0
3,0.0,NaN,0.0,0.0,8.0,8.0,8.0,8.0,1.033,21.911175,...,4.0,1.0,2.0,2.0,3.0,8.0,2.0,888.0,12.9,3.0
4,0.0,NaN,0.0,0.0,5.0,8.0,8.0,8.0,1.008,18.993831,...,8.0,1.0,8.0,2.0,1.0,8.0,1.0,20.0,13.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86347,8.0,0.0,0.0,NaN,5.0,8.0,8.0,8.0,1.012,29.098956,...,NaN,8.0,NaN,8.0,1.0,NaN,8.0,NaN,16.8,3.0
86348,8.0,0.0,0.0,NaN,8.0,8.0,8.0,8.0,1.008,21.230572,...,NaN,8.0,NaN,8.0,2.0,NaN,8.0,NaN,14.7,1.0
86349,8.0,0.0,0.0,NaN,5.0,8.0,8.0,8.0,1.018,28.400548,...,NaN,8.0,NaN,8.0,1.0,NaN,8.0,NaN,17.1,3.0
86350,8.0,0.0,0.0,NaN,5.0,0.0,0.0,0.0,1.012,20.905450,...,NaN,8.0,NaN,8.0,2.0,NaN,8.0,NaN,12.2,3.0
86351,8.0,8.0,0.0,NaN,5.0,8.0,8.0,8.0,1.014,21.988857,...,NaN,8.0,NaN,8.0,1.0,NaN,2.0,NaN,13.0,3.0

In [7]:
targets

['DK8_dg',
 'BO3_05',
 'HE_Uket',
 'HE_fh',
 'BA2_12',
 'LQ4_03',
 'LQ4_15',
 'LQ4_21',
 'HE_Usg',
 'HE_BMI',
 'BE3_82',
 'DQ_MILK',
 'HE_STRfh1',
 'BM2_1',
 'BD2',
 'T_Q_DZ6',
 'E_CLT',
 'T_NQ_OCP',
 'BM7',
 'BM13_3',
 'E_CLC',
 'LW_pr_1',
 'D_2_wk',
 'DM4_pr',
 'DC3_pr',
 'BS12_1',
 'BE3_72',
 'T_Q_DZ5',
 'BP16_11',
 'L_OUT_FQ',
 'DJ8_pr',
 'LQ2_mn',
 'DI1_dg',
 'BP6_10',
 'HE_Uro',
 'DJ4_pr',
 'BM2_3',
 'DH3_dg',
 'HE_BUN',
 'HE_cough2',
 'E_EM',
 'DM8_pt',
 'HE_LDL_drct',
 'EC1_1',
 'LQ_1EQL',
 'LQ4_08',
 'DQ_SODA',
 'incm',
 'BA2_2_3',
 'LQ4_06',
 'DC5_pr',
 'LQ4_04',
 'E_PEO_1',
 'BS9_2',
 'BH9_11',
 'house',
 'HE_HTG',
 'T_Q_SNST2',
 'DK4_pr',
 'LW_mt',
 'BA2_2_2',
 'T_IM_EX_L_1',
 'MO4_18',
 'BS6_2',
 'BE3_85',
 'HE_sbp',
 'L_DN_TO',
 'BM1_7',
 'HE_STRfh2',
 'DE2_pr',
 'BO1_1',
 'HE_chol',
 'T_Q_CR',
 'HE_HLfh2',
 'LQ4_11',
 'HE_df',
 'ID_fam',
 'DH4_dg',
 'LQ4_00',
 'HE_HBfh3',
 'HE_sput1',
 'LQ1_mn',
 'DC1_pt',
 'EC_stt_1',
 'E_DR',
 'HE_Uglu',
 'HE_prg',
 'HE_fev1p',
 'DK8_pt',
 'DH7_pt',
 'EC_occp',
 'DC11_pt',
 'DJ2_pr',
 'HE_DM_HbA1c',
 'BM1_5',
 'ID',
 'BM13',
 'LQ4_01',
 'E_DG',
 'HE_THfh2',
 'MH1_1',
 'BS12_2',
 'BP16_13',
 'BA2_2_4',
 'DL1_pr',
 'E_CL_pr',
 'ainc_1',
 'O_ortho',
 'DI2_pr',
 'ainc',
 'DC1_pr',
 'DM1_pr',
 'L_BR_WHO',
 'HE_HP',
 'BE8_1',
 'HE_pef',
 'graduat',
 'LQ4_23',
 'T_VHIT_EX_L_1',
 'allownc',
 'OR1_2',
 'E_NWT',
 'BE3_91',
 'BM1_1',
 'BP1',
 'LQ4_13',
 'genertn',
 'DH7_dg',
 'DM8_dg',
 'LW_oc',
 'LQ4_29',
 'LQ4_09',
 'E_CLD',
 'BO3_10',
 'LK_LB_US',
 'E_RT',
 'DC7_pt',
 'BA2_14',
 'BA2_13',
 'year',
 'BH1',
 'BM2_2',
 'HE_obe',
 'ho_incm',
 'DC12_pr',
 'BO3_11',
 'HE_Unitr',
 'DC5_dg',
 'DM4_pt',
 'E_Cr_1',
 'DM3_pt',
 'HE_HDL_st2',
 'LW_ms_a',
 'LQ4_16',
 'BE3_32',
 'T_Q_VN_1',
 'BM13_1',
 'BS5_1',
 'DC6_pt',
 'DI3_pr',
 'HE_hepaC',
 'HE_dog',
 'HE_DMfh3',
 'BP5',
 'DJ4_3',
 'HE_HbA1c',
 'HE_hepaB',
 'live_t',
 'DI2_pt',
 'DH4_pt',
 'LQ_4EQL',
 'DH3_pr',
 'DK4_dg',
 'BE3_93',
 'BM14',
 'LQ_4HT',
 'HE_HCT',
 'DJ6_pr',
 'D_2_1',
 'sex',
 'DI2_2',
 'LW_mt_a2',
 'EC_pedu_2',
 'BO3_14',
 'HE_Uph',
 'L_BR_TO',
 'DC3_pt',
 'DC12_pt',
 'occp',
 'HE_cough1',
 'HE_ht',
 'DQ_SMILK',
 'BD1',
 'LQ4_22',
 'HE_wc',
 'E_NMRC_r',
 'BE5_1',
 'HE_HLfh3',
 'T_VHIT_GA_R',
 'HE_cat',
 'BO3_03',
 'BO3_12',
 'T_Q_HR',
 'BP7',
 'HE_wt',
 'LQ4_10',
 'BS3_3',
 'LQ_5EQL',
 'HE_fev6',
 'LK_LB_EF',
 'LW_ms',
 'O_chew_d',
 'LQ4_26',
 'LS_FRUIT',
 'E_Pr_1',
 'cfam',
 'HE_DMfh2',
 'BM1_4',
 'HE_STRfh3',
 'BS12_37',
 'BA2_2_6',
 'DC11_dg',
 'D_1_1',
 'HE_DMdr',
 'HE_ast',
 'T_Q_VN',
 'DN1_dg',
 'DH7_pr',
 'MO4_17_2',
 'EC_wht_5',
 'E_CT',
 'E_NMRC_l',
 'DQ_CAFFEINE',
 'T_Q_ALLE',
 'HE_HPfh2',
 'DK4_pt',
 'DK9_dg',
 'BD7_62',
 'LQ4_07',
 'L_LN_WHO',
 'BE3_83',
 'HE_PFThs',
 'MO4_8',
 'T_VHIT_EX_R',
 'HE_ragweed',
 'E_MH',
 'E_DR1',
 'HE_RBC',
 'E_GR',
 'T_Q_DZ3',
 'DI4_pt',
 'HE_HPfh3',
 'BS12_47',
 'DJ2_pt',
 'DK9_pr',
 'LQ_7HT',
 'DC11_pr',
 'LQ4_14',
 'DJ6_dg',
 'T_Q_DZ4',
 'DM2_pt',
 'HE_fvcp',
 'E_Pl_1',
 'EC_wht_23',
 'E_Dl_2_1',
 'T_VHIT_COR_R',
 'LW_br',
 'LQ2_ab',
 'HE_fev1',
 'BP16_23',
 'BE3_86',
 'HE_sput2',
 'DN1_pr',
 'HE_HBfh1',
 'T_Q_SNST1',
 'E_CLC_T',
 'DM8_pr',
 'DC6_pr',
 'DM3_pr',
 'DJ4_dg',
 'HE_glu',
 'HE_HPfh1',
 'DI1_2',
 'HE_THfh3',
 'DC1_dg',
 'DI3_pt',
 'T_Q_CR3',
 'MO4_00',
 'T_VHIT_GA_L',
 'T_Q_HR_1',
 'BM2_5',
 'HE_IHDfh3',
 'LW_mt_a1',
 'BE3_75',
 'DQ_YOGURT',
 'E_DME',
 'BA2_2_1',
 'E_CLU',
 'educ',
 'L_LN_TO',
 'LQ4_12',
 'BA2_2_5',
 'DJ8_pt',
 'DE2_pt',
 'L_BR_FQ',
 'HE_Uacid',
 'marri_1',
 'DE1_pt',
 'EC_stt_2',
 'HE_Bplt',
 'HE_birch',
 'E_Cl_1',
 'DC4_dg',
 'BD2_1',
 'DC12_dg',
 'HE_fev1fvc',
 'DC4_pt',
 'BE3_31',
 'BS6_3',
 'T_IM_EX_R_1',
 'DC4_pr',
 'DM4_dg',
 'DC6_dg',
 'MO4_15',
 'LS_VEG1',
 'DH3_pt',
 'HE_HCHOL',
 'DC2_pr',
 'T_Q_CR4',
 'DQ_TEA',
 'ainc_unit1',
 'T_VHIT_EX_R_1',
 'HE_Ubld',
 'T_Q_VC',
 'HE_dbp',
 'BS6_4',
 'T_IM_EX_R',
 'BO3_09',
 'BM1_6',
 'BO1',
 'BS1_1',
 'LQ_6HT',
 'DE1_pr',
 'DJ8_dg',
 'BD7_65',
 'MO4_17_1',
 'T_Q_DZ',
 'HE_Upro',
 'T_ex',
 'LQ_2HT',
 'HE_WBC',
 'BO3_02',
 'DH6_pr',
 'E_DG1',
 'HE_TG',
 'HE_mens',
 'T_IM_EX_L',
 'BH2_61',
 'BD1_11',
 'DI4_pr',
 'BD7_5',
 'E_AMD',
 'BO2_1',
 'DQ_COFFEE',
 'DC2_pt',
 'DL1_pt',
 'DN1_pt',
 'T_Q_VN_2',
 'MO4_17',
 'HE_oak',
 'DJ4_pt',
 'BE3_71',
 'BP6_2',
 'L_DN_WHO',
 'DK8_pr',
 'DH6_dg',
 'MO4_9',
 'T_Q_VC1',
 'DI3_dg',
 'DH2_pr',
 'BM13_4',
 'HE_DMfh1',
 'DI4_dg',
 'HE_fvc',
 'DJ2_dg',
 'DI1_pt',
 'M_2_yr',
 'BE3_77',
 'HE_fef25_75',
 'BO3_01',
 'DK9_pt',
 'DM1_dg',
 'BM1_3',
 'BE3_92',
 'HE_HBfh2',
 'BM2_4',
 'HE_HLfh1',
 'HE_PFTtr',
 'BM1_8',
 'DI2_dg',
 'marri_2',
 'DC3_dg',
 'LQ4_25',
 'age',
 'HE_IHDfh2',
 'HE_PFTdr',
 'MO4_12',
 'T_Q_DZ7',
 'T_Q_SINU',
 'BP16_2',
 'EC_pedu_1',
 'LW_mp_a',
 'BP16_1',
 'BP16_21',
 'BS5',
 'HE_Ualb',
 'BP16_12',
 'BS3_2',
 'HE_Ucot',
 'E_DM',
 'BO3_04',
 'LQ_2EQL',
 'DH4_pr',
 'T_Q_CR2',
 'DQ_STEA',
 'T_VHIT_COR_L',
 'BD7_61',
 'LQ_3EQL',
 'ho_incm5',
 'BM13_2',
 'E_PEO',
 'BS12_47_1',
 'BM8',
 'BS13',
 'HE_COPD',
 'HE_nc',
 'DC7_pr',
 'LW_pr',
 'L_DN_FQ',
 'DH6_pt',
 'BH2_62',
 'T_Q_SNST3',
 'LQ1_sb',
 'T_Q_SINU_1',
 'DM2_dg',
 'BE3_87',
 'DC7_dg',
 'BE3_73',
 'HE_Ubil',
 'incm5',
 'HE_crea',
 'pa_aerobic',
 'T_Q_DZ2',
 'DI1_pr',
 'MO4_7',
 'LK_LB_CO',
 'BO1_3',
 'HE_HPdr',
 'HE_PFTag',
 'HE_insulin',
 'HE_IHDfh1',
 'BM1_2',
 'DI3_2',
 'L_LN_FQ',
 'BS3_1',
 'BD7_64',
 'LQ_8HT',
 'HE_UNa',
 'T_Q_CR1',
 'T_VHIT_EX_L',
 'DJ6_pt',
 'DH2_pt',
 'BS5_4',
 'LQ_5HT',
 'BM13_5',
 'E_EXC_1',
 'HE_Ukal',
 'LQ_1HT',
 'DM3_dg',
 'BD7_63',
 'DM2_pr',
 'LQ4_05',
 'DE1_dg',
 'MO4_11',
 'BM14_1',
 'T_Q_SNST4',
 'HE_Ucrea',
 'BE3_81',
 'HE_anem',
 'MH1_yr',
 'HE_Jhop',
 'DL1_dg',
 'DC5_pt',
 'O_pain',
 'LS_VEG2',
 'HE_THfh1',
 'BO3_07',
 'E_ex',
 'DE2_dg',
 'DQ_SCOFFEE',
 'LQ4_28',
 'DH2_dg',
 'LQ_3HT',
 'E_RVO',
 'HE_rPLS',
 'BO1_2',
 'DM1_pt',
 'LQ4_02',
 'DC2_dg',
 'HE_dprg',
 'HE_alt',
 'E_Q_EX',
 'E_Dr_2_1',
 'BD7_66',
 'T_Q_HR_2',
 'BE3_76',
 'MO4_4',
 'EC_wht_0',
 'BP6_31',
 'fam_rela',
 'LQ4_27',
 'BS8_2',
 'BS2_2',
 'HE_HB',
 'edu']

In [5]:
# 각 컬럼별 결측치 비율 계산
missing_ratio = df[targets].isnull().mean()

# 결측치 비율이 30% 이상인 컬럼 제거
df_cleaned = df[targets].loc[:, missing_ratio < 0.3]
df_cleaned
# for col in df_cleaned.columns:
#     print(col)

,DK8_dg,BO3_05,HE_Uket,BA2_12,LQ4_03,LQ4_15,LQ4_21,HE_Usg,HE_BMI,HE_STRfh1,...,LQ4_02,DC2_dg,HE_alt,MO4_4,EC_wht_0,BP6_31,fam_rela,BS8_2,HE_HB,edu
0,0.0,NaN,0.0,8.0,8.0,8.0,8.0,1.013,26.789017,0.0,...,8.0,0.0,61.0,1.0,2.0,2.0,1.0,2.0,15.2,3.0
1,0.0,NaN,0.0,2.0,8.0,8.0,8.0,1.014,25.506641,0.0,...,8.0,0.0,24.0,1.0,2.0,2.0,9.0,2.0,15.1,3.0
2,0.0,NaN,0.0,8.0,8.0,8.0,8.0,1.013,23.075711,0.0,...,8.0,0.0,14.0,8.0,2.0,2.0,1.0,2.0,13.3,2.0
3,0.0,NaN,0.0,8.0,8.0,8.0,8.0,1.033,21.911175,0.0,...,8.0,0.0,9.0,1.0,2.0,2.0,3.0,2.0,12.9,3.0
4,0.0,NaN,0.0,5.0,8.0,8.0,8.0,1.008,18.993831,0.0,...,8.0,0.0,10.0,1.0,8.0,2.0,1.0,1.0,13.1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86347,8.0,0.0,0.0,5.0,8.0,8.0,8.0,1.012,29.098956,9.0,...,8.0,8.0,46.0,8.0,NaN,8.0,1.0,8.0,16.8,3.0
86348,8.0,0.0,0.0,8.0,8.0,8.0,8.0,1.008,21.230572,9.0,...,8.0,8.0,12.0,8.0,NaN,8.0,2.0,8.0,14.7,1.0
86349,8.0,0.0,0.0,5.0,8.0,8.0,8.0,1.018,28.400548,9.0,...,8.0,8.0,45.0,8.0,NaN,8.0,1.0,8.0,17.1,3.0
86350,8.0,0.0,0.0,5.0,0.0,0.0,0.0,1.012,20.905450,0.0,...,0.0,8.0,12.0,8.0,NaN,8.0,2.0,8.0,12.2,3.0
86351,8.0,8.0,0.0,5.0,8.0,8.0,8.0,1.014,21.988857,0.0,...,8.0,8.0,11.0,8.0,NaN,8.0,1.0,2.0,13.0,3.0