In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/HN__4_8__19__selected.csv')

/var/folders/3y/hj83hdwn2nn49jp7jks64t480000gn/T/ipykernel_38089/2308605726.py:4: DtypeWarning: Columns (205) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/HN__4_8__19__selected.csv')

In [2]:
## v2+v3 반영.  
## ['LQ4_24', 'N_DT_DS', 'N_DUSUAL', 'N_DAY'] object 타입이라 뺌
## [9, 99, 999, 9999] 무응답 널처리

####### 얘네 빼도 되는지 확인 - object 타입인 녀석들 ####
df = df.drop(columns=['LQ4_24', 'N_DT_DS', 'N_DUSUAL', 'N_DAY'], inplace=False)

####### 9, 99, 999 인 녀석들 null 처리
df = df.replace([9, 99, 999, 9999], np.nan, inplace=False)

In [3]:
cond = df["BP_PHQ_1"].notna() & \
        df["BP_PHQ_2"].notna() & \
        df["BP_PHQ_3"].notna() & \
        df["BP_PHQ_4"].notna() & \
        df["BP_PHQ_5"].notna() & \
        df["BP_PHQ_6"].notna() & \
        df["BP_PHQ_7"].notna() & \
        df["BP_PHQ_8"].notna() & \
        df["BP_PHQ_9"].notna()

df[df["mh_PHQ_S"].isnull() & cond][["BP_PHQ_1", "BP_PHQ_2", "BP_PHQ_3", "BP_PHQ_4", "BP_PHQ_5", "BP_PHQ_6", "BP_PHQ_7", "BP_PHQ_8", "BP_PHQ_9"]].value_counts()

BP_PHQ_1  BP_PHQ_2  BP_PHQ_3  BP_PHQ_4  BP_PHQ_5  BP_PHQ_6  BP_PHQ_7  BP_PHQ_8  BP_PHQ_9
0.0       0.0       3.0       3.0       3.0       0.0       0.0       0.0       0.0         26
3.0       0.0       3.0       3.0       0.0       0.0       0.0       0.0       0.0         11
1.0       1.0       1.0       1.0       1.0       1.0       1.0       1.0       1.0          7
3.0       3.0       0.0       3.0       0.0       0.0       0.0       0.0       0.0          5
1.0       1.0       3.0       2.0       2.0       0.0       0.0       0.0       0.0          4
                                                                                            ..
          0.0       3.0       2.0       3.0       0.0       0.0       0.0       0.0          1
                              3.0       0.0       0.0       0.0       2.0       0.0          1
                                                  1.0       1.0       0.0       0.0          1
          1.0       0.0       2.0       2.0       1.0       0.0       0.0       2.0          1
                    1.0       2.0       2.0       1.0       1.0       0.0       0.0          1
Name: count, Length: 247, dtype: int64

In [4]:
a = df[df["mh_PHQ_S"].isnull() & cond][["BP_PHQ_1", "BP_PHQ_2", "BP_PHQ_3", "BP_PHQ_4", "BP_PHQ_5", "BP_PHQ_6", "BP_PHQ_7", "BP_PHQ_8", "BP_PHQ_9"]]

b = a[a <= 3].sum(axis=1)
b[b >= 1] #125

df['mh_PHQ_S'] = b[b >=1]

In [5]:
# row 기준 
threshold = 0.3 # threshold for null proportion
null_percent = df.isnull().mean(axis = 1) # 각 행에 대한 결측값 비율 계산
df = df[null_percent < threshold]
df

,cfam,house,live_t,ainc,sex,age,marri_1,marri_2,tins,npins,...,mh_PHQ_S,BP_GAD_1,BP_GAD_2,BP_GAD_3,BP_GAD_4,BP_GAD_5,BP_GAD_6,BP_GAD_7,mh_GAD_S,DF2_pr
0,2.0,1.0,2.0,460.833333,1.0,61.0,2.0,88.0,20.0,1.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,1.0,2.0,460.833333,1.0,57.0,1.0,4.0,20.0,1.0,...,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,8.0
2,2.0,1.0,2.0,257.500000,2.0,39.0,1.0,4.0,20.0,1.0,...,NaN,1.0,0.0,2.0,1.0,0.0,1.0,0.0,5.0,8.0
3,2.0,1.0,2.0,257.500000,2.0,19.0,2.0,88.0,20.0,2.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
4,2.0,1.0,2.0,133.750000,1.0,70.0,1.0,1.0,20.0,1.0,...,NaN,1.0,1.0,2.0,0.0,0.0,0.0,0.0,4.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94110,1.0,1.0,1.0,NaN,2.0,74.0,1.0,3.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
94113,3.0,2.0,1.0,58.333333,1.0,75.0,1.0,1.0,20.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
94114,3.0,2.0,1.0,58.333333,2.0,74.0,1.0,1.0,20.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
94117,4.0,2.0,1.0,200.000000,2.0,34.0,1.0,1.0,10.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
94118,4.0,2.0,1.0,150.000000,2.0,65.0,1.0,1.0,10.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

In [6]:
# Define depression (dependent variable)
cond1 = df['mh_PHQ_S'] >= 10 # total score 
cond2 = df['BP_PHQ_9'].isin([1, 2, 3]) # person who chose 1, 2, 3 in 9th question

df[cond1 | cond2].drop_duplicates() # person with cond1 or cond2

,cfam,house,live_t,ainc,sex,age,marri_1,marri_2,tins,npins,...,mh_PHQ_S,BP_GAD_1,BP_GAD_2,BP_GAD_3,BP_GAD_4,BP_GAD_5,BP_GAD_6,BP_GAD_7,mh_GAD_S,DF2_pr
6015,3.0,3.0,2.0,820.000000,2.0,52.0,1.0,1.0,20.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
6042,5.0,2.0,2.0,698.333333,2.0,53.0,1.0,1.0,20.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
6055,4.0,1.0,1.0,250.000000,1.0,27.0,2.0,88.0,20.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
6082,4.0,1.0,1.0,170.000000,1.0,43.0,1.0,1.0,10.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
6144,4.0,2.0,2.0,530.000000,1.0,27.0,2.0,88.0,20.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49897,2.0,2.0,3.0,225.000000,2.0,37.0,1.0,4.0,10.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
49924,1.0,2.0,1.0,46.666667,2.0,80.0,1.0,3.0,10.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49948,4.0,3.0,2.0,380.000000,1.0,46.0,1.0,1.0,20.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49958,3.0,2.0,2.0,583.333333,1.0,55.0,1.0,1.0,10.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49987,2.0,3.0,2.0,800.000000,2.0,26.0,2.0,88.0,20.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

In [7]:
# Create a new variable 'depressed' 
df.loc[cond1 | cond2, 'depressed'] = 1 # 두 조건 중 하나 이상을 만족하는 행에 'depressed' 변수에 1 값 
df.loc[~(cond1 | cond2), 'depressed'] = 0 # 두 조건 중 하나라도 만족하지 않는 행에 0 값

In [8]:
# Check distribution of depressed to see if the data is imbalanced
df.groupby('depressed').count() # groupby를 이용해 타겟 y 라벨의 클래스 별 개수를 확인

,cfam,house,live_t,ainc,sex,age,marri_1,marri_2,tins,npins,...,mh_PHQ_S,BP_GAD_1,BP_GAD_2,BP_GAD_3,BP_GAD_4,BP_GAD_5,BP_GAD_6,BP_GAD_7,mh_GAD_S,DF2_pr
depressed,,,,,,,,,,,,,,,,,,,,,
0.0,81518,81487,81516,80810,81538,81538,81477,81446,81027,80654,...,242,5324,5323,5322,5322,5322,5322,5322,5249,81537
1.0,1387,1386,1387,1385,1387,1387,1387,1386,1372,1375,...,93,0,0,0,0,0,0,0,0,1387

In [9]:
df[df['DF2_pr'].isna() & df['mh_PHQ_S'].isna()] # 0개

,cfam,house,live_t,ainc,sex,age,marri_1,marri_2,tins,npins,...,BP_GAD_1,BP_GAD_2,BP_GAD_3,BP_GAD_4,BP_GAD_5,BP_GAD_6,BP_GAD_7,mh_GAD_S,DF2_pr,depressed
72171,4.0,3.0,2.0,833.333333,2.0,46.0,1.0,1.0,10.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [10]:
# Remove people who might be depressed
# DF2_pr == 8 (never been diagnosed by doctor) & mh_PHQ_S == NaN) 인 경우를 제외하려면?
# DF2_pr != 8 or mh_PHQ != NaN (전부 다 ~ 취하기)
df = df[(df['DF2_pr'] != 8 |  ~df['mh_PHQ_S'].isna())]
df.shape

(80331, 224)

In [11]:
# Remove columns if percentage of NaN exceeds 0.1
threshold = 0.3 # 이거로 하나, 0.1로 하나 큰 차이 x
threshold = 0.1 

null_percent = df.isnull().mean() # 각 열에 대한 결측값 비율 계산
selected_cols = null_percent[null_percent < threshold].index
df = df[selected_cols]
df.shape # (20492, 314)

(80331, 157)

In [12]:
df.isnull().sum().sort_values(ascending = False) # 결측치 개수 확인

EC_occp      7174
EC_pedu_2    6976
EC_lgw_4     6396
HE_BUN       5547
BH9_11       5134
             ...
DJ4_pr          0
DJ4_pt          0
DE1_dg          0
DE1_pr          0
depressed       0
Length: 157, dtype: int64

In [13]:
# df2 = df.dropna()
# "depressed" in df2.columns # True
# df2[df2['depressed'] == 1]

In [14]:
# X = df2.drop('depressed', axis = 1)

In [15]:
#TODO fillna
from sklearn.impute import KNNImputer

X = df.drop('depressed', axis = 1) 
X.shape #(89331, 156)

###TODO
imputer = KNNImputer(n_neighbors=5)
X_new = imputer.fit_transform(X)
X_new

/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

array([[2., 1., 2., ..., 0., 0., 0.],
       [2., 1., 2., ..., 0., 0., 8.],
       [2., 1., 2., ..., 0., 0., 8.],
       ...,
       [3., 2., 1., ..., 1., 1., 8.],
       [4., 2., 1., ..., 1., 1., 8.],
       [4., 2., 1., ..., 0., 1., 8.]])

In [20]:
df_new = pd.DataFrame(X_new, columns=df.drop('depressed', axis = 1).columns)
df_new.isna().sum().sort_values(ascending = False)

cfam      0
BM1_6     0
BE3_31    0
BE5_1     0
BM1_1     0
         ..
LQ4_11    0
LQ4_12    0
LQ4_13    0
LQ4_14    0
DF2_pr    0
Length: 156, dtype: int64

In [21]:
#TODO scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit_transform(df_new)
df_with_scaled = pd.DataFrame(scaler.fit_transform(df_new), columns=df_new.columns)
df_with_scaled

/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

,cfam,house,live_t,ainc,sex,age,marri_1,marri_2,tins,npins,...,HE_Uph,HE_Unitr,HE_Usg,HE_Upro,HE_Uglu,HE_Uket,HE_Ubil,HE_Ubld,HE_Uro,DF2_pr
0,0.2,0.0,0.25,0.299438,0.0,0.688525,1.0,1.000000,0.5,0.0,...,0.285714,0.0,0.26,0.0,0.0,0.0,0.0,0.0,0.00,0.0
1,0.2,0.0,0.25,0.299438,0.0,0.622951,0.0,0.034483,0.5,0.0,...,0.000000,0.0,0.28,0.0,0.0,0.0,0.0,0.0,0.00,1.0
2,0.2,0.0,0.25,0.162360,1.0,0.327869,0.0,0.034483,0.5,0.0,...,0.285714,0.0,0.26,0.0,0.0,0.0,0.0,0.0,0.00,1.0
3,0.2,0.0,0.25,0.162360,1.0,0.000000,1.0,1.000000,0.5,1.0,...,0.285714,0.0,0.66,0.2,0.0,0.0,0.0,0.0,0.00,1.0
4,0.2,0.0,0.25,0.078933,0.0,0.836066,0.0,0.000000,0.5,0.0,...,0.714286,0.0,0.16,0.0,0.0,0.0,0.0,0.0,0.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80326,0.0,0.0,0.00,0.048494,1.0,0.901639,0.0,0.022989,0.4,1.0,...,0.000000,0.0,0.50,0.0,0.0,0.0,0.0,0.8,0.25,1.0
80327,0.4,0.5,0.00,0.028090,0.0,0.918033,0.0,0.000000,0.5,1.0,...,0.000000,0.0,0.50,0.0,0.0,0.0,0.0,0.4,0.25,1.0
80328,0.4,0.5,0.00,0.028090,1.0,0.901639,0.0,0.000000,0.5,1.0,...,0.000000,0.0,0.30,0.0,0.0,0.0,0.0,0.2,0.25,1.0
80329,0.6,0.5,0.00,0.123596,1.0,0.245902,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.60,0.0,0.0,0.0,0.0,0.2,0.25,1.0
80330,0.6,0.5,0.00,0.089888,1.0,0.754098,0.0,0.000000,0.0,1.0,...,0.285714,0.0,0.20,0.0,0.0,0.0,0.0,0.0,0.25,1.0

In [26]:
# under sampling.  OVER 만 하기엔 너무 많이 생성해야해서 under 선수행
from imblearn.under_sampling import RandomUnderSampler

X = df_with_scaled
y = df['depressed']

rus = RandomUnderSampler(sampling_strategy=0.1, random_state=42)
X_under, y_under = rus.fit_resample(X, y)

X_under.shape

/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

(12584, 156)

In [27]:
#TODO over sampling
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_over, y_over = smote.fit_resample(X_under, y_under)

X_over.shape, y_over.shape

/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

((22880, 156), (22880,))

In [30]:
y_over.value_counts()

depressed
0.0    11440
1.0    11440
Name: count, dtype: int64

In [100]:
# TODO 데이터 시각화
# temp = pd.DataFrame(X_res)
# temp['y_label'] = y_res

# plt.scatter(temp[temp['label']==0], temp[temp['label']==0], label='0')
# plt.scatter(temp[temp['label']==1], temp[temp['label']==1], label='1')
# plt.title("SMOTE - Over-sampled Data")
# plt.legend()
# plt.show()

Original dataset shape Counter({0.0: 66031, 1.0: 1006})

/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/ijong-won/miniconda3/envs/torch-nightly/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

Resampled dataset shape Counter({0.0: 66031, 1.0: 66031})

/var/folders/3y/hj83hdwn2nn49jp7jks64t480000gn/T/ipykernel_27186/2805469819.py:31: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  temp['y_label'] = y_res

In [31]:
X_over.to_csv('../data/HN_X_over.csv', index=False)
y_over.to_csv('../data/HN_y_over.csv', index=False)