In [ ]:
import pandas as pd

df_origin = pd.read_csv('../data/HN_cardinal_1_8.csv')
df_origin.groupby('cardinal_number').size()

In [122]:
#1. 현재 y 값. 그럼 비해당 인원들은?
#2. y값 변수들을 PH9로 바꾼다.  PH9 을 만들어서~

#TODO ph9 비율 체크
# df_origin["BP_PHQ_1"].info() #29422
# df_origin["mh_PHQ_S"].info() #21977
# df_origin[df_origin["mh_PHQ_S"] >= 5] #-> #1257(10점:중증), 4309(5점:경증)

# df_origin[df_origin["mh_PHQ_S"] >= 10]["year"].unique() # [2020, 2018, 2016, 2014]

# import numpy as np
# df_origin["mh_PHQ_S_flag"] = np.where(df_origin["mh_PHQ_S"] >= 10, 1, 0)

# aa = df_origin.query("mh_PHQ_S_flag == 1 or DF2_pr == 1") #3680
# aa[["mh_PHQ_S", "mh_PHQ_S_flag", "DF2_pr"]]

,mod_d,ID,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,F_kc_rds,F_lett,F_leek,F_ssm_lv,F_garlic,F_mallow,F_dropwt,F_broc,cardinal_number,mh_PHQ_S_flag
7100,2023.07.11.,A801177904,A8011779,2020.0,1.0,1.0,2.0,A801,1.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0
7118,2023.07.11.,A801230604,A8012306,2020.0,1.0,1.0,2.0,A801,2.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0
7131,2023.07.11.,A801244202,A8012442,2020.0,1.0,1.0,2.0,A801,2.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0
7143,2023.07.11.,A801364902,A8013649,2020.0,1.0,1.0,2.0,A801,1.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0
7154,2023.07.11.,A802252702,A8022527,2020.0,1.0,1.0,2.0,A802,2.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61721,2022.03.08,NaN,P2467570,2014.0,16.0,1.0,2.0,P246,1.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,0
61722,2022.03.08,NaN,P2467621,2014.0,16.0,1.0,2.0,P246,1.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,0
61728,2022.03.08,NaN,P2467672,2014.0,16.0,1.0,2.0,P246,1.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,0
61739,2022.03.08,NaN,P2467842,2014.0,16.0,1.0,2.0,P246,2.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1
61756,2022.03.08,NaN,P2468165,2014.0,16.0,1.0,2.0,P246,2.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,0

In [ ]:
tartgets = [
    'cardinal_number',
    "DF2_pr",
    'DK8_dg',
 'BO3_05',
 'HE_Uket',
 'HE_fh',
 'BA2_12',
 'LQ4_03',
 'LQ4_15',
 'LQ4_21',
 'HE_Usg',
 'HE_BMI',
 'BE3_82',
 'DQ_MILK',
 'HE_STRfh1',
 'BM2_1',
 'BD2',
 'T_Q_DZ6',
 'E_CLT',
 'T_NQ_OCP',
 'BM7',
 'BM13_3',
 'E_CLC',
 'LW_pr_1',
 'D_2_wk',
 'DM4_pr',
 'DC3_pr',
 'BS12_1',
 'BE3_72',
 'T_Q_DZ5',
 'BP16_11',
 'L_OUT_FQ',
 'DJ8_pr',
 'LQ2_mn',
 'DI1_dg',
 'BP6_10',
 'HE_Uro',
 'DJ4_pr',
 'BM2_3',
 'DH3_dg',
 'HE_BUN',
 'HE_cough2',
 'E_EM',
 'DM8_pt',
 'HE_LDL_drct',
 'EC1_1',
 'LQ_1EQL',
 'LQ4_08',
 'DQ_SODA',
 'incm',
 'BA2_2_3',
 'LQ4_06',
 'DC5_pr',
 'LQ4_04',
 'E_PEO_1',
 'BS9_2',
 'BH9_11',
 'house',
 'HE_HTG',
 'T_Q_SNST2',
 'DK4_pr',
 'LW_mt',
 'BA2_2_2',
 'T_IM_EX_L_1',
 'MO4_18',
 'BS6_2',
 'BE3_85',
 'HE_sbp',
 'L_DN_TO',
 'BM1_7',
 'HE_STRfh2',
 'DE2_pr',
 'BO1_1',
 'HE_chol',
 'T_Q_CR',
 'HE_HLfh2',
 'LQ4_11',
 'HE_df',
 'ID_fam',
 'DH4_dg',
 'LQ4_00',
 'HE_HBfh3',
 'HE_sput1',
 'LQ1_mn',
 'DC1_pt',
 'EC_stt_1',
 'E_DR',
 'HE_Uglu',
 'HE_prg',
 'HE_fev1p',
 'DK8_pt',
 'DH7_pt',
 'EC_occp',
 'DC11_pt',
 'DJ2_pr',
 'HE_DM_HbA1c',
 'BM1_5',
 'ID',
 'BM13',
 'LQ4_01',
 'E_DG',
 'HE_THfh2',
 'MH1_1',
 'BS12_2',
 'BP16_13',
 'BA2_2_4',
 'DL1_pr',
 'E_CL_pr',
 'ainc_1',
 'O_ortho',
 'DI2_pr',
 'ainc',
 'DC1_pr',
 'DM1_pr',
 'L_BR_WHO',
 'HE_HP',
 'BE8_1',
 'HE_pef',
 'graduat',
 'LQ4_23',
 'T_VHIT_EX_L_1',
 'allownc',
 'OR1_2',
 'E_NWT',
 'BE3_91',
 'BM1_1',
 'BP1',
 'LQ4_13',
 'genertn',
 'DH7_dg',
 'DM8_dg',
 'LW_oc',
 'LQ4_29',
 'LQ4_09',
 'E_CLD',
 'BO3_10',
 'LK_LB_US',
 'E_RT',
 'DC7_pt',
 'BA2_14',
 'BA2_13',
 'year',
 'BH1',
 'BM2_2',
 'HE_obe',
 'ho_incm',
 'DC12_pr',
 'BO3_11',
 'HE_Unitr',
 'DC5_dg',
 'DM4_pt',
 'E_Cr_1',
 'DM3_pt',
 'HE_HDL_st2',
 'LW_ms_a',
 'LQ4_16',
 'BE3_32',
 'T_Q_VN_1',
 'BM13_1',
 'BS5_1',
 'DC6_pt',
 'DI3_pr',
 'HE_hepaC',
 'HE_dog',
 'HE_DMfh3',
 'BP5',
 'DJ4_3',
 'HE_HbA1c',
 'HE_hepaB',
 'live_t',
 'DI2_pt',
 'DH4_pt',
 'LQ_4EQL',
 'DH3_pr',
 'DK4_dg',
 'BE3_93',
 'BM14',
 'LQ_4HT',
 'HE_HCT',
 'DJ6_pr',
 'D_2_1',
 'sex',
 'DI2_2',
 'LW_mt_a2',
 'EC_pedu_2',
 'BO3_14',
 'HE_Uph',
 'L_BR_TO',
 'DC3_pt',
 'DC12_pt',
 'occp',
 'HE_cough1',
 'HE_ht',
 'DQ_SMILK',
 'BD1',
 'LQ4_22',
 'HE_wc',
 'E_NMRC_r',
 'BE5_1',
 'HE_HLfh3',
 'T_VHIT_GA_R',
 'HE_cat',
 'BO3_03',
 'BO3_12',
 'T_Q_HR',
 'BP7',
 'HE_wt',
 'LQ4_10',
 'BS3_3',
 'LQ_5EQL',
 'HE_fev6',
 'LK_LB_EF',
 'LW_ms',
 'O_chew_d',
 'LQ4_26',
 'LS_FRUIT',
 'E_Pr_1',
 'cfam',
 'HE_DMfh2',
 'BM1_4',
 'HE_STRfh3',
 'BS12_37',
 'BA2_2_6',
 'DC11_dg',
 'D_1_1',
 'HE_DMdr',
 'HE_ast',
 'T_Q_VN',
 'DN1_dg',
 'DH7_pr',
 'MO4_17_2',
 'EC_wht_5',
 'E_CT',
 'E_NMRC_l',
 'DQ_CAFFEINE',
 'T_Q_ALLE',
 'HE_HPfh2',
 'DK4_pt',
 'DK9_dg',
 'BD7_62',
 'LQ4_07',
 'L_LN_WHO',
 'BE3_83',
 'HE_PFThs',
 'MO4_8',
 'T_VHIT_EX_R',
 'HE_ragweed',
 'E_MH',
 'E_DR1',
 'HE_RBC',
 'E_GR',
 'T_Q_DZ3',
 'DI4_pt',
 'HE_HPfh3',
 'BS12_47',
 'DJ2_pt',
 'DK9_pr',
 'LQ_7HT',
 'DC11_pr',
 'LQ4_14',
 'DJ6_dg',
 'T_Q_DZ4',
 'DM2_pt',
 'HE_fvcp',
 'E_Pl_1',
 'EC_wht_23',
 'E_Dl_2_1',
 'T_VHIT_COR_R',
 'LW_br',
 'LQ2_ab',
 'HE_fev1',
 'BP16_23',
 'BE3_86',
 'HE_sput2',
 'DN1_pr',
 'HE_HBfh1',
 'T_Q_SNST1',
 'E_CLC_T',
 'DM8_pr',
 'DC6_pr',
 'DM3_pr',
 'DJ4_dg',
 'HE_glu',
 'HE_HPfh1',
 'DI1_2',
 'HE_THfh3',
 'DC1_dg',
 'DI3_pt',
 'T_Q_CR3',
 'MO4_00',
 'T_VHIT_GA_L',
 'T_Q_HR_1',
 'BM2_5',
 'HE_IHDfh3',
 'LW_mt_a1',
 'BE3_75',
 'DQ_YOGURT',
 'E_DME',
 'BA2_2_1',
 'E_CLU',
 'educ',
 'L_LN_TO',
 'LQ4_12',
 'BA2_2_5',
 'DJ8_pt',
 'DE2_pt',
 'L_BR_FQ',
 'HE_Uacid',
 'marri_1',
 'DE1_pt',
 'EC_stt_2',
 'HE_Bplt',
 'HE_birch',
 'E_Cl_1',
 'DC4_dg',
 'BD2_1',
 'DC12_dg',
 'HE_fev1fvc',
 'DC4_pt',
 'BE3_31',
 'BS6_3',
 'T_IM_EX_R_1',
 'DC4_pr',
 'DM4_dg',
 'DC6_dg',
 'MO4_15',
 'LS_VEG1',
 'DH3_pt',
 'HE_HCHOL',
 'DC2_pr',
 'T_Q_CR4',
 'DQ_TEA',
 'ainc_unit1',
 'T_VHIT_EX_R_1',
 'HE_Ubld',
 'T_Q_VC',
 'HE_dbp',
 'BS6_4',
 'T_IM_EX_R',
 'BO3_09',
 'BM1_6',
 'BO1',
 'BS1_1',
 'LQ_6HT',
 'DE1_pr',
 'DJ8_dg',
 'BD7_65',
 'MO4_17_1',
 'T_Q_DZ',
 'HE_Upro',
 'T_ex',
 'LQ_2HT',
 'HE_WBC',
 'BO3_02',
 'DH6_pr',
 'E_DG1',
 'HE_TG',
 'HE_mens',
 'T_IM_EX_L',
 'BH2_61',
 'BD1_11',
 'DI4_pr',
 'BD7_5',
 'E_AMD',
 'BO2_1',
 'DQ_COFFEE',
 'DC2_pt',
 'DL1_pt',
 'DN1_pt',
 'T_Q_VN_2',
 'MO4_17',
 'HE_oak',
 'DJ4_pt',
 'BE3_71',
 'BP6_2',
 'L_DN_WHO',
 'DK8_pr',
 'DH6_dg',
 'MO4_9',
 'T_Q_VC1',
 'DI3_dg',
 'DH2_pr',
 'BM13_4',
 'HE_DMfh1',
 'DI4_dg',
 'HE_fvc',
 'DJ2_dg',
 'DI1_pt',
 'M_2_yr',
 'BE3_77',
 'HE_fef25_75',
 'BO3_01',
 'DK9_pt',
 'DM1_dg',
 'BM1_3',
 'BE3_92',
 'HE_HBfh2',
 'BM2_4',
 'HE_HLfh1',
 'HE_PFTtr',
 'BM1_8',
 'DI2_dg',
 'marri_2',
 'DC3_dg',
 'LQ4_25',
 'age',
 'HE_IHDfh2',
 'HE_PFTdr',
 'MO4_12',
 'T_Q_DZ7',
 'T_Q_SINU',
 'BP16_2',
 'EC_pedu_1',
 'LW_mp_a',
 'BP16_1',
 'BP16_21',
 'BS5',
 'HE_Ualb',
 'BP16_12',
 'BS3_2',
 'HE_Ucot',
 'E_DM',
 'BO3_04',
 'LQ_2EQL',
 'DH4_pr',
 'T_Q_CR2',
 'DQ_STEA',
 'T_VHIT_COR_L',
 'BD7_61',
 'LQ_3EQL',
 'ho_incm5',
 'BM13_2',
 'E_PEO',
 'BS12_47_1',
 'BM8',
 'BS13',
 'HE_COPD',
 'HE_nc',
 'DC7_pr',
 'LW_pr',
 'L_DN_FQ',
 'DH6_pt',
 'BH2_62',
 'T_Q_SNST3',
 'LQ1_sb',
 'T_Q_SINU_1',
 'DM2_dg',
 'BE3_87',
 'DC7_dg',
 'BE3_73',
 'HE_Ubil',
 'incm5',
 'HE_crea',
 'pa_aerobic',
 'T_Q_DZ2',
 'DI1_pr',
 'MO4_7',
 'LK_LB_CO',
 'BO1_3',
 'HE_HPdr',
 'HE_PFTag',
 'HE_insulin',
 'HE_IHDfh1',
 'BM1_2',
 'DI3_2',
 'L_LN_FQ',
 'BS3_1',
 'BD7_64',
 'LQ_8HT',
 'HE_UNa',
 'T_Q_CR1',
 'T_VHIT_EX_L',
 'DJ6_pt',
 'DH2_pt',
 'BS5_4',
 'LQ_5HT',
 'BM13_5',
 'E_EXC_1',
 'HE_Ukal',
 'LQ_1HT',
 'DM3_dg',
 'BD7_63',
 'DM2_pr',
 'LQ4_05',
 'DE1_dg',
 'MO4_11',
 'BM14_1',
 'T_Q_SNST4',
 'HE_Ucrea',
 'BE3_81',
 'HE_anem',
 'MH1_yr',
 'HE_Jhop',
 'DL1_dg',
 'DC5_pt',
 'O_pain',
 'LS_VEG2',
 'HE_THfh1',
 'BO3_07',
 'E_ex',
 'DE2_dg',
 'DQ_SCOFFEE',
 'LQ4_28',
 'DH2_dg',
 'LQ_3HT',
 'E_RVO',
 'HE_rPLS',
 'BO1_2',
 'DM1_pt',
 'LQ4_02',
 'DC2_dg',
 'HE_dprg',
 'HE_alt',
 'E_Q_EX',
 'E_Dr_2_1',
 'BD7_66',
 'T_Q_HR_2',
 'BE3_76',
 'MO4_4',
 'EC_wht_0',
 'BP6_31',
 'fam_rela',
 'LQ4_27',
 'BS8_2',
 'BS2_2',
 'HE_HB',
 'edu']

df = df_origin[tartgets]
df

In [ ]:
df.to_csv('../data/HN_cardinal_1_8_lightweight.csv', index=False)

In [ ]:
# object 필드 제거
drop_lst = ['E_CLT', 'E_PEO_1', 'ID_fam', 'BO3_11', 'E_DR1', 'E_CLC_T',
       'E_DG1']
df = df.drop(columns = drop_lst)

# 만19세 이상인 사용자만 분리해서 사용
df = df[df['age']>=19]
df

In [ ]:
df['cardinal_number'] = pd.to_numeric(df['cardinal_number'])


# for car_num in range(1,8):
#     for ratio in [0.1, 0.3, 0.5]:
#         not_one = df[df['cardinal_number'] > car_num]
#         missing_ratio = not_one.isnull().mean()

#         df_cleaned = not_one.loc[:, missing_ratio < ratio]
#         print(f"car_num = {car_num}, ratio = {ratio}, df_cleaned.shape = {df_cleaned.shape}")

In [ ]:
car_num = 4
ratio = 0.3

#car_num = 4, ratio = 0.3, df_cleaned.shape = (75713, 284)
df = df[df['cardinal_number'] > car_num]
df = df.loc[:, df.isnull().mean() < ratio]
df.shape

In [ ]:
#car_num = 4, ratio = 0.3, df_cleaned.shape = (75713, 284)
df.to_csv("./save_point_01.csv", index=False)

In [ ]:
df.query("DF2_pr == 1")["DF2_pr"]
#TODO 3~25배

In [ ]:
null_standard = [9, 99, 999]
# count_matching_values = df[df.isin(null_standard)].shape[0]
# count_matching_values = df.isin(null_standard).shape[0]

df2 = df.fillna(9999, inplace=False)
df2

In [132]:
# rows = 75713
df_y_true = df2[df['DF2_pr'] == 1]

In [133]:

df_y_true_multiple_2 = pd.concat([df_y_true]*2, ignore_index=True).reset_index()
df_y_true_multiple_2

,index,cardinal_number,DF2_pr,DK8_dg,BO3_05,HE_Uket,HE_fh,BA2_12,LQ4_03,LQ4_15,...,DM1_pt,LQ4_02,DC2_dg,HE_alt,MO4_4,BP6_31,fam_rela,BS8_2,HE_HB,edu
0,0,8,1.0,0.0,9999.0,0.0,1.0,8.0,8.0,8.0,...,1.0,8.0,0.0,49.0,1.0,2.0,2.0,8.0,15.0,2.0
1,1,8,1.0,1.0,9999.0,0.0,0.0,8.0,8.0,8.0,...,1.0,8.0,0.0,18.0,1.0,2.0,2.0,8.0,12.5,4.0
2,2,8,1.0,0.0,9999.0,0.0,1.0,5.0,8.0,8.0,...,8.0,8.0,0.0,14.0,1.0,2.0,2.0,8.0,13.3,4.0
3,3,8,1.0,0.0,9999.0,0.0,0.0,8.0,8.0,8.0,...,0.0,8.0,0.0,18.0,1.0,1.0,3.0,8.0,13.3,4.0
4,4,8,1.0,0.0,9999.0,0.0,1.0,5.0,0.0,0.0,...,8.0,0.0,0.0,47.0,1.0,2.0,1.0,8.0,16.3,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3605,3605,5,1.0,8.0,0.0,0.0,1.0,8.0,0.0,0.0,...,8.0,0.0,8.0,14.0,8.0,2.0,1.0,8.0,14.5,1.0
3606,3606,5,1.0,8.0,8.0,0.0,0.0,8.0,8.0,8.0,...,8.0,8.0,8.0,12.0,8.0,2.0,1.0,1.0,13.5,1.0
3607,3607,5,1.0,8.0,0.0,0.0,0.0,4.0,8.0,8.0,...,1.0,8.0,8.0,23.0,8.0,8.0,2.0,8.0,14.4,1.0
3608,3608,5,1.0,8.0,0.0,0.0,0.0,8.0,8.0,8.0,...,8.0,8.0,8.0,21.0,0.0,2.0,1.0,1.0,12.9,1.0
3609,3609,5,1.0,8.0,0.0,0.0,1.0,3.0,8.0,8.0,...,8.0,8.0,8.0,9999.0,8.0,2.0,3.0,8.0,9999.0,4.0

In [134]:
df_y_false = df2[df['DF2_pr'] == 0]

In [135]:
# 청소년, 소아, !!!의사진단 받지 않음!!!
# -> 이게 애매해서 PHQ9 으로 판단하는 방법도 있음
#TODO PHQ9 필드 추가하는게 좋을듯
# df2[df['DF2_pr'] == 8]
# => 해당 없음이 너무 많아서 y 주제 논의했었음.

In [136]:
df3 = pd.concat([df_y_true_multiple_2, df_y_false], ignore_index=True).reset_index()
df3

,level_0,index,cardinal_number,DF2_pr,DK8_dg,BO3_05,HE_Uket,HE_fh,BA2_12,LQ4_03,...,DM1_pt,LQ4_02,DC2_dg,HE_alt,MO4_4,BP6_31,fam_rela,BS8_2,HE_HB,edu
0,0,0.0,8,1.0,0.0,9999.0,0.0,1.0,8.0,8.0,...,1.0,8.0,0.0,49.0,1.0,2.0,2.0,8.0,15.0,2.0
1,1,1.0,8,1.0,1.0,9999.0,0.0,0.0,8.0,8.0,...,1.0,8.0,0.0,18.0,1.0,2.0,2.0,8.0,12.5,4.0
2,2,2.0,8,1.0,0.0,9999.0,0.0,1.0,5.0,8.0,...,8.0,8.0,0.0,14.0,1.0,2.0,2.0,8.0,13.3,4.0
3,3,3.0,8,1.0,0.0,9999.0,0.0,0.0,8.0,8.0,...,0.0,8.0,0.0,18.0,1.0,1.0,3.0,8.0,13.3,4.0
4,4,4.0,8,1.0,0.0,9999.0,0.0,1.0,5.0,0.0,...,8.0,0.0,0.0,47.0,1.0,2.0,1.0,8.0,16.3,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6921,6921,NaN,5,0.0,8.0,8.0,0.0,0.0,5.0,8.0,...,1.0,8.0,8.0,19.0,8.0,8.0,2.0,1.0,13.6,3.0
6922,6922,NaN,5,0.0,8.0,8.0,0.0,0.0,3.0,8.0,...,8.0,8.0,8.0,77.0,8.0,8.0,3.0,2.0,14.8,3.0
6923,6923,NaN,5,0.0,8.0,0.0,0.0,1.0,4.0,8.0,...,8.0,8.0,8.0,20.0,8.0,8.0,1.0,8.0,13.3,3.0
6924,6924,NaN,5,0.0,8.0,0.0,9999.0,0.0,8.0,8.0,...,8.0,8.0,8.0,12.0,8.0,2.0,1.0,2.0,13.2,3.0
6925,6925,NaN,5,0.0,8.0,0.0,0.0,1.0,5.0,8.0,...,8.0,8.0,8.0,27.0,8.0,8.0,2.0,1.0,14.1,4.0

In [144]:
df3[df3["DF2_pr"] == 0] 

aa = df3.query("DF2_pr == 0 and mh_PHQ_S >= 5 ")

UndefinedVariableError: name 'mh_PHQ_S' is not defined

In [142]:
df3.drop(columns=["level_0","index"]).to_csv("./training_data_202311291425.csv", index=False)